name:                smt2fp
version:             0.1.0.0
github:              "gokhankici/smt2fp"
license:             BSD3
author:              "Rami Gokhan Kici"
maintainer:          "gokhankici@gmail.com"
copyright:           "2018 Rami Gokhan Kici"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/gokhankici/smt2fp#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- pretty
- lens
- unordered-containers
- mtl

library:
  source-dirs: src
  ghc-options:
  - -W

executables:
  smt2fp:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smt2fp
    - ansi-terminal

tests:
  smt2fp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smt2fp
